package panels;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.FocusListener;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import utility.Utilities;
public class CylinderMeasurePanel extends JPanel {
  private JTextField diameterText;
  private JTextField lengthText;
  private JTextField ambientTempText;
  private JTextField baseTempText;
  public CylinderMeasurePanel(){
    super(new BorderLayout());
    java.awt.BorderLayout genVar867;
    genVar867=new BorderLayout();
    JPanel panelLeft;
    panelLeft=new JPanel(genVar867);
    java.awt.BorderLayout genVar868;
    genVar868=new BorderLayout();
    JPanel panelRight;
    panelRight=new JPanel(genVar868);
    int genVar869;
    genVar869=5;
    int genVar870;
    genVar870=5;
    int genVar871;
    genVar871=5;
    int genVar872;
    genVar872=5;
    javax.swing.border.Border genVar873;
    genVar873=BorderFactory.createEmptyBorder(genVar869,genVar870,genVar871,genVar872);
    panelLeft.setBorder(genVar873);
    java.lang.String genVar874;
    genVar874="Diameter";
    JLabel diameterLabel;
    diameterLabel=new JLabel(genVar874);
    int genVar875;
    genVar875=10;
    diameterText=new JTextField(genVar875);
    diameterText.setBorder(Utilities.normalBorder);
    java.lang.String genVar876;
    genVar876="Length";
    JLabel lengthLabel;
    lengthLabel=new JLabel(genVar876);
    int genVar877;
    genVar877=10;
    lengthText=new JTextField(genVar877);
    lengthText.setBorder(Utilities.normalBorder);
    int genVar878;
    genVar878=0;
    int genVar879;
    genVar879=1;
    int genVar880;
    genVar880=1;
    int genVar881;
    genVar881=1;
    java.awt.GridLayout genVar882;
    genVar882=new GridLayout(genVar878,genVar879,genVar880,genVar881);
    JPanel leftLabels;
    leftLabels=new JPanel(genVar882);
    int genVar883;
    genVar883=3;
    int genVar884;
    genVar884=3;
    int genVar885;
    genVar885=3;
    int genVar886;
    genVar886=3;
    javax.swing.border.Border genVar887;
    genVar887=BorderFactory.createEmptyBorder(genVar883,genVar884,genVar885,genVar886);
    leftLabels.setBorder(genVar887);
    int genVar888;
    genVar888=0;
    int genVar889;
    genVar889=1;
    int genVar890;
    genVar890=1;
    int genVar891;
    genVar891=1;
    java.awt.GridLayout genVar892;
    genVar892=new GridLayout(genVar888,genVar889,genVar890,genVar891);
    JPanel leftFields;
    leftFields=new JPanel(genVar892);
    leftLabels.add(diameterLabel);
    leftLabels.add(lengthLabel);
    leftFields.add(diameterText);
    leftFields.add(lengthText);
    panelLeft.add(leftLabels,BorderLayout.WEST);
    panelLeft.add(leftFields,BorderLayout.EAST);
    diameterText.addFocusListener(Utilities.focusListener);
    lengthText.addFocusListener(Utilities.focusListener);
    int genVar893;
    genVar893=5;
    int genVar894;
    genVar894=5;
    int genVar895;
    genVar895=5;
    int genVar896;
    genVar896=5;
    javax.swing.border.Border genVar897;
    genVar897=BorderFactory.createEmptyBorder(genVar893,genVar894,genVar895,genVar896);
    panelRight.setBorder(genVar897);
    int genVar898;
    genVar898=0;
    int genVar899;
    genVar899=1;
    int genVar900;
    genVar900=1;
    int genVar901;
    genVar901=1;
    java.awt.GridLayout genVar902;
    genVar902=new GridLayout(genVar898,genVar899,genVar900,genVar901);
    JPanel rightLabels;
    rightLabels=new JPanel(genVar902);
    int genVar903;
    genVar903=5;
    int genVar904;
    genVar904=5;
    int genVar905;
    genVar905=5;
    int genVar906;
    genVar906=5;
    javax.swing.border.Border genVar907;
    genVar907=BorderFactory.createEmptyBorder(genVar903,genVar904,genVar905,genVar906);
    rightLabels.setBorder(genVar907);
    int genVar908;
    genVar908=0;
    int genVar909;
    genVar909=1;
    int genVar910;
    genVar910=1;
    int genVar911;
    genVar911=1;
    java.awt.GridLayout genVar912;
    genVar912=new GridLayout(genVar908,genVar909,genVar910,genVar911);
    JPanel rightFields;
    rightFields=new JPanel(genVar912);
    int genVar913;
    genVar913=5;
    int genVar914;
    genVar914=5;
    int genVar915;
    genVar915=5;
    int genVar916;
    genVar916=5;
    javax.swing.border.Border genVar917;
    genVar917=BorderFactory.createEmptyBorder(genVar913,genVar914,genVar915,genVar916);
    rightFields.setBorder(genVar917);
    java.lang.String genVar918;
    genVar918="Ambient Temperature";
    JLabel ambientTempLabel;
    ambientTempLabel=new JLabel(genVar918);
    int genVar919;
    genVar919=10;
    ambientTempText=new JTextField(genVar919);
    ambientTempText.setBorder(Utilities.normalBorder);
    java.lang.String genVar920;
    genVar920="Base Temperature";
    JLabel baseTempLabel;
    baseTempLabel=new JLabel(genVar920);
    int genVar921;
    genVar921=10;
    baseTempText=new JTextField(genVar921);
    baseTempText.setBorder(Utilities.normalBorder);
    rightLabels.add(ambientTempLabel);
    rightLabels.add(baseTempLabel);
    rightFields.add(ambientTempText);
    rightFields.add(baseTempText);
    panelRight.add(rightLabels,BorderLayout.WEST);
    panelRight.add(rightFields,BorderLayout.CENTER);
    panels.CylinderMeasurePanel genVar922;
    genVar922=this;
    genVar922.add(panelLeft,BorderLayout.WEST);
    panels.CylinderMeasurePanel genVar923;
    genVar923=this;
    genVar923.add(panelRight,BorderLayout.EAST);
    ambientTempText.addFocusListener(Utilities.focusListener);
    baseTempText.addFocusListener(Utilities.focusListener);
  }
  public double getDiameter(){
    java.lang.String genVar924;
    genVar924=diameterText.getText();
    double genVar925;
    genVar925=Double.parseDouble(genVar924);
    return genVar925;
  }
  public double getLength(){
    java.lang.String genVar926;
    genVar926=lengthText.getText();
    double genVar927;
    genVar927=Double.parseDouble(genVar926);
    return genVar927;
  }
  public double getAmbientTemp(){
    java.lang.String genVar928;
    genVar928=ambientTempText.getText();
    double genVar929;
    genVar929=Double.parseDouble(genVar928);
    return genVar929;
  }
  public double getBaseTemp(){
    java.lang.String genVar930;
    genVar930=baseTempText.getText();
    double genVar931;
    genVar931=Double.parseDouble(genVar930);
    return genVar931;
  }
  public void setDiameterFocus(  FocusListener focusListener){
    diameterText.addFocusListener(focusListener);
  }
  public void setLengthFocus(  FocusListener focusListener){
    lengthText.addFocusListener(focusListener);
  }
}
