package panels;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.FocusListener;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import utility.Utilities;
public class TrapezoidalMeasurePanel extends JPanel {
  private JTextField base1Text;
  private JTextField base2Text;
  private JTextField heightText;
  private JTextField ambientTempText;
  private JTextField baseTempText;
  public TrapezoidalMeasurePanel(){
    super(new BorderLayout());
    java.awt.BorderLayout genVar454;
    genVar454=new BorderLayout();
    JPanel panelLeft;
    panelLeft=new JPanel(genVar454);
    java.awt.BorderLayout genVar455;
    genVar455=new BorderLayout();
    JPanel panelRight;
    panelRight=new JPanel(genVar455);
    int genVar456;
    genVar456=5;
    int genVar457;
    genVar457=5;
    int genVar458;
    genVar458=5;
    int genVar459;
    genVar459=5;
    javax.swing.border.Border genVar460;
    genVar460=BorderFactory.createEmptyBorder(genVar456,genVar457,genVar458,genVar459);
    panelLeft.setBorder(genVar460);
    java.lang.String genVar461;
    genVar461="Base";
    JLabel base1Label;
    base1Label=new JLabel(genVar461);
    int genVar462;
    genVar462=10;
    base1Text=new JTextField(genVar462);
    base1Text.setBorder(Utilities.normalBorder);
    java.lang.String genVar463;
    genVar463="Base";
    JLabel base2Label;
    base2Label=new JLabel(genVar463);
    int genVar464;
    genVar464=10;
    base2Text=new JTextField(genVar464);
    base2Text.setBorder(Utilities.normalBorder);
    java.lang.String genVar465;
    genVar465="Height";
    JLabel heightLabel;
    heightLabel=new JLabel(genVar465);
    int genVar466;
    genVar466=10;
    heightText=new JTextField(genVar466);
    heightText.setBorder(Utilities.normalBorder);
    int genVar467;
    genVar467=0;
    int genVar468;
    genVar468=1;
    int genVar469;
    genVar469=1;
    int genVar470;
    genVar470=1;
    java.awt.GridLayout genVar471;
    genVar471=new GridLayout(genVar467,genVar468,genVar469,genVar470);
    JPanel leftLabels;
    leftLabels=new JPanel(genVar471);
    int genVar472;
    genVar472=3;
    int genVar473;
    genVar473=3;
    int genVar474;
    genVar474=3;
    int genVar475;
    genVar475=3;
    javax.swing.border.Border genVar476;
    genVar476=BorderFactory.createEmptyBorder(genVar472,genVar473,genVar474,genVar475);
    leftLabels.setBorder(genVar476);
    int genVar477;
    genVar477=0;
    int genVar478;
    genVar478=1;
    int genVar479;
    genVar479=1;
    int genVar480;
    genVar480=1;
    java.awt.GridLayout genVar481;
    genVar481=new GridLayout(genVar477,genVar478,genVar479,genVar480);
    JPanel leftFields;
    leftFields=new JPanel(genVar481);
    leftLabels.add(base1Label);
    leftLabels.add(base2Label);
    leftLabels.add(heightLabel);
    leftFields.add(base1Text);
    leftFields.add(base2Text);
    leftFields.add(heightText);
    panelLeft.add(leftLabels,BorderLayout.WEST);
    panelLeft.add(leftFields,BorderLayout.EAST);
    base1Text.addFocusListener(Utilities.focusListener);
    base2Text.addFocusListener(Utilities.focusListener);
    heightText.addFocusListener(Utilities.focusListener);
    int genVar482;
    genVar482=5;
    int genVar483;
    genVar483=5;
    int genVar484;
    genVar484=5;
    int genVar485;
    genVar485=5;
    javax.swing.border.Border genVar486;
    genVar486=BorderFactory.createEmptyBorder(genVar482,genVar483,genVar484,genVar485);
    panelRight.setBorder(genVar486);
    int genVar487;
    genVar487=0;
    int genVar488;
    genVar488=1;
    int genVar489;
    genVar489=1;
    int genVar490;
    genVar490=1;
    java.awt.GridLayout genVar491;
    genVar491=new GridLayout(genVar487,genVar488,genVar489,genVar490);
    JPanel rightLabels;
    rightLabels=new JPanel(genVar491);
    int genVar492;
    genVar492=5;
    int genVar493;
    genVar493=5;
    int genVar494;
    genVar494=5;
    int genVar495;
    genVar495=5;
    javax.swing.border.Border genVar496;
    genVar496=BorderFactory.createEmptyBorder(genVar492,genVar493,genVar494,genVar495);
    rightLabels.setBorder(genVar496);
    int genVar497;
    genVar497=0;
    int genVar498;
    genVar498=1;
    int genVar499;
    genVar499=1;
    int genVar500;
    genVar500=1;
    java.awt.GridLayout genVar501;
    genVar501=new GridLayout(genVar497,genVar498,genVar499,genVar500);
    JPanel rightFields;
    rightFields=new JPanel(genVar501);
    int genVar502;
    genVar502=5;
    int genVar503;
    genVar503=5;
    int genVar504;
    genVar504=5;
    int genVar505;
    genVar505=5;
    javax.swing.border.Border genVar506;
    genVar506=BorderFactory.createEmptyBorder(genVar502,genVar503,genVar504,genVar505);
    rightFields.setBorder(genVar506);
    java.lang.String genVar507;
    genVar507="Ambient Temperature";
    JLabel ambientTempLabel;
    ambientTempLabel=new JLabel(genVar507);
    int genVar508;
    genVar508=10;
    ambientTempText=new JTextField(genVar508);
    ambientTempText.setBorder(Utilities.normalBorder);
    java.lang.String genVar509;
    genVar509="Base Temperature";
    JLabel baseTempLabel;
    baseTempLabel=new JLabel(genVar509);
    int genVar510;
    genVar510=10;
    baseTempText=new JTextField(genVar510);
    baseTempText.setBorder(Utilities.normalBorder);
    rightLabels.add(ambientTempLabel);
    rightLabels.add(baseTempLabel);
    rightFields.add(ambientTempText);
    rightFields.add(baseTempText);
    panelRight.add(rightLabels,BorderLayout.WEST);
    panelRight.add(rightFields,BorderLayout.CENTER);
    panels.TrapezoidalMeasurePanel genVar511;
    genVar511=this;
    genVar511.add(panelLeft,BorderLayout.WEST);
    panels.TrapezoidalMeasurePanel genVar512;
    genVar512=this;
    genVar512.add(panelRight,BorderLayout.EAST);
    ambientTempText.addFocusListener(Utilities.focusListener);
    baseTempText.addFocusListener(Utilities.focusListener);
  }
  public double getBase1(){
    java.lang.String genVar513;
    genVar513=base1Text.getText();
    double genVar514;
    genVar514=Double.parseDouble(genVar513);
    return genVar514;
  }
  public double getBase2(){
    java.lang.String genVar515;
    genVar515=base2Text.getText();
    double genVar516;
    genVar516=Double.parseDouble(genVar515);
    return genVar516;
  }
  public double getHeightF(){
    java.lang.String genVar517;
    genVar517=heightText.getText();
    double genVar518;
    genVar518=Double.parseDouble(genVar517);
    return genVar518;
  }
  public double getAmbientTemp(){
    java.lang.String genVar519;
    genVar519=ambientTempText.getText();
    double genVar520;
    genVar520=Double.parseDouble(genVar519);
    return genVar520;
  }
  public double getBaseTemp(){
    java.lang.String genVar521;
    genVar521=baseTempText.getText();
    double genVar522;
    genVar522=Double.parseDouble(genVar521);
    return genVar522;
  }
  public void setBase1Focus(  FocusListener focusListener){
    base1Text.addFocusListener(focusListener);
  }
  public void setBase2Focus(  FocusListener focusListener){
    base2Text.addFocusListener(focusListener);
  }
  public void setHeightFocus(  FocusListener focusListener){
    heightText.addFocusListener(focusListener);
  }
}
