package panels;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.FocusListener;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import utility.Utilities;
public class TriangleMeasurePanel extends JPanel {
  private JTextField lengthText;
  private JTextField widthText;
  private JTextField thicknessText;
  private JTextField ambientTempText;
  private JTextField baseTempText;
  public TriangleMeasurePanel(){
    super(new BorderLayout());
    java.awt.BorderLayout genVar384;
    genVar384=new BorderLayout();
    JPanel panelLeft;
    panelLeft=new JPanel(genVar384);
    java.awt.BorderLayout genVar385;
    genVar385=new BorderLayout();
    JPanel panelRight;
    panelRight=new JPanel(genVar385);
    int genVar386;
    genVar386=5;
    int genVar387;
    genVar387=5;
    int genVar388;
    genVar388=5;
    int genVar389;
    genVar389=5;
    javax.swing.border.Border genVar390;
    genVar390=BorderFactory.createEmptyBorder(genVar386,genVar387,genVar388,genVar389);
    panelLeft.setBorder(genVar390);
    java.lang.String genVar391;
    genVar391="Length";
    JLabel lengthLabel;
    lengthLabel=new JLabel(genVar391);
    int genVar392;
    genVar392=10;
    lengthText=new JTextField(genVar392);
    lengthText.setBorder(Utilities.normalBorder);
    java.lang.String genVar393;
    genVar393="Width";
    JLabel widthLabel;
    widthLabel=new JLabel(genVar393);
    int genVar394;
    genVar394=10;
    widthText=new JTextField(genVar394);
    widthText.setBorder(Utilities.normalBorder);
    java.lang.String genVar395;
    genVar395="Thickness";
    JLabel thicknessLabel;
    thicknessLabel=new JLabel(genVar395);
    int genVar396;
    genVar396=10;
    thicknessText=new JTextField(genVar396);
    thicknessText.setBorder(Utilities.normalBorder);
    int genVar397;
    genVar397=0;
    int genVar398;
    genVar398=1;
    int genVar399;
    genVar399=1;
    int genVar400;
    genVar400=1;
    java.awt.GridLayout genVar401;
    genVar401=new GridLayout(genVar397,genVar398,genVar399,genVar400);
    JPanel leftLabels;
    leftLabels=new JPanel(genVar401);
    int genVar402;
    genVar402=3;
    int genVar403;
    genVar403=3;
    int genVar404;
    genVar404=3;
    int genVar405;
    genVar405=3;
    javax.swing.border.Border genVar406;
    genVar406=BorderFactory.createEmptyBorder(genVar402,genVar403,genVar404,genVar405);
    leftLabels.setBorder(genVar406);
    int genVar407;
    genVar407=0;
    int genVar408;
    genVar408=1;
    int genVar409;
    genVar409=1;
    int genVar410;
    genVar410=1;
    java.awt.GridLayout genVar411;
    genVar411=new GridLayout(genVar407,genVar408,genVar409,genVar410);
    JPanel leftFields;
    leftFields=new JPanel(genVar411);
    leftLabels.add(lengthLabel);
    leftLabels.add(widthLabel);
    leftLabels.add(thicknessLabel);
    leftFields.add(lengthText);
    leftFields.add(widthText);
    leftFields.add(thicknessText);
    panelLeft.add(leftLabels,BorderLayout.WEST);
    panelLeft.add(leftFields,BorderLayout.EAST);
    lengthText.addFocusListener(Utilities.focusListener);
    widthText.addFocusListener(Utilities.focusListener);
    thicknessText.addFocusListener(Utilities.focusListener);
    int genVar412;
    genVar412=5;
    int genVar413;
    genVar413=5;
    int genVar414;
    genVar414=5;
    int genVar415;
    genVar415=5;
    javax.swing.border.Border genVar416;
    genVar416=BorderFactory.createEmptyBorder(genVar412,genVar413,genVar414,genVar415);
    panelRight.setBorder(genVar416);
    int genVar417;
    genVar417=0;
    int genVar418;
    genVar418=1;
    int genVar419;
    genVar419=1;
    int genVar420;
    genVar420=1;
    java.awt.GridLayout genVar421;
    genVar421=new GridLayout(genVar417,genVar418,genVar419,genVar420);
    JPanel rightLabels;
    rightLabels=new JPanel(genVar421);
    int genVar422;
    genVar422=5;
    int genVar423;
    genVar423=5;
    int genVar424;
    genVar424=5;
    int genVar425;
    genVar425=5;
    javax.swing.border.Border genVar426;
    genVar426=BorderFactory.createEmptyBorder(genVar422,genVar423,genVar424,genVar425);
    rightLabels.setBorder(genVar426);
    int genVar427;
    genVar427=0;
    int genVar428;
    genVar428=1;
    int genVar429;
    genVar429=1;
    int genVar430;
    genVar430=1;
    java.awt.GridLayout genVar431;
    genVar431=new GridLayout(genVar427,genVar428,genVar429,genVar430);
    JPanel rightFields;
    rightFields=new JPanel(genVar431);
    int genVar432;
    genVar432=5;
    int genVar433;
    genVar433=5;
    int genVar434;
    genVar434=5;
    int genVar435;
    genVar435=5;
    javax.swing.border.Border genVar436;
    genVar436=BorderFactory.createEmptyBorder(genVar432,genVar433,genVar434,genVar435);
    rightFields.setBorder(genVar436);
    java.lang.String genVar437;
    genVar437="Ambient Temperature";
    JLabel ambientTempLabel;
    ambientTempLabel=new JLabel(genVar437);
    int genVar438;
    genVar438=10;
    ambientTempText=new JTextField(genVar438);
    ambientTempText.setBorder(Utilities.normalBorder);
    java.lang.String genVar439;
    genVar439="Base Temperature";
    JLabel baseTempLabel;
    baseTempLabel=new JLabel(genVar439);
    int genVar440;
    genVar440=10;
    baseTempText=new JTextField(genVar440);
    baseTempText.setBorder(Utilities.normalBorder);
    rightLabels.add(ambientTempLabel);
    rightLabels.add(baseTempLabel);
    rightFields.add(ambientTempText);
    rightFields.add(baseTempText);
    panelRight.add(rightLabels,BorderLayout.WEST);
    panelRight.add(rightFields,BorderLayout.CENTER);
    panels.TriangleMeasurePanel genVar441;
    genVar441=this;
    genVar441.add(panelLeft,BorderLayout.WEST);
    panels.TriangleMeasurePanel genVar442;
    genVar442=this;
    genVar442.add(panelRight,BorderLayout.EAST);
    ambientTempText.addFocusListener(Utilities.focusListener);
    baseTempText.addFocusListener(Utilities.focusListener);
  }
  public double getLength(){
    java.lang.String genVar443;
    genVar443=lengthText.getText();
    double genVar444;
    genVar444=Double.parseDouble(genVar443);
    return genVar444;
  }
  public double getWidthF(){
    java.lang.String genVar445;
    genVar445=widthText.getText();
    double genVar446;
    genVar446=Double.parseDouble(genVar445);
    return genVar446;
  }
  public double getThickness(){
    java.lang.String genVar447;
    genVar447=thicknessText.getText();
    double genVar448;
    genVar448=Double.parseDouble(genVar447);
    return genVar448;
  }
  public double getAmbientTemp(){
    java.lang.String genVar449;
    genVar449=ambientTempText.getText();
    double genVar450;
    genVar450=Double.parseDouble(genVar449);
    return genVar450;
  }
  public double getBaseTemp(){
    java.lang.String genVar451;
    genVar451=baseTempText.getText();
    double genVar452;
    genVar452=Double.parseDouble(genVar451);
    return genVar452;
  }
  public void setLengthFocus(  FocusListener focusListener){
    lengthText.addFocusListener(focusListener);
  }
  public void setWidthFocus(  FocusListener focusListener){
    widthText.addFocusListener(focusListener);
  }
  public void setThicknessFocus(  FocusListener focusListener){
    thicknessText.addFocusListener(focusListener);
  }
}
