//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.28 at 07:17:01 PM MESZ 
//


package org.openfuxml.renderer.data.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfuxml.renderer.data.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfuxml.renderer.data.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Merge }
     * 
     */
    public Merge createMerge() {
        return new Merge();
    }

    /**
     * Create an instance of {@link Cmp }
     * 
     */
    public Cmp createCmp() {
        return new Cmp();
    }

    /**
     * Create an instance of {@link Toc }
     * 
     */
    public Toc createToc() {
        return new Toc();
    }

    /**
     * Create an instance of {@link Preprocessor }
     * 
     */
    public Preprocessor createPreprocessor() {
        return new Preprocessor();
    }

    /**
     * Create an instance of {@link Targets }
     * 
     */
    public Targets createTargets() {
        return new Targets();
    }

    /**
     * Create an instance of {@link Wiki }
     * 
     */
    public Wiki createWiki() {
        return new Wiki();
    }

    /**
     * Create an instance of {@link Pdf }
     * 
     */
    public Pdf createPdf() {
        return new Pdf();
    }

}
