//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.04 at 09:07:41 AM MEZ 
//


package org.openfuxml.addon.chart.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timeseries">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="gap" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="cumulate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="timePeriod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="timebar">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="shadow" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="gradient" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="bar">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="vertical" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="gantt">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="timePeriod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="spline" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timeseries",
    "timebar",
    "bar",
    "gantt",
    "spline"
})
@XmlRootElement(name = "charttype")
public class Charttype
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected Charttype.Timeseries timeseries;
    @XmlElement(required = true)
    protected Charttype.Timebar timebar;
    @XmlElement(required = true)
    protected Charttype.Bar bar;
    @XmlElement(required = true)
    protected Charttype.Gantt gantt;
    @XmlElement(required = true)
    protected Object spline;

    /**
     * Gets the value of the timeseries property.
     * 
     * @return
     *     possible object is
     *     {@link Charttype.Timeseries }
     *     
     */
    public Charttype.Timeseries getTimeseries() {
        return timeseries;
    }

    /**
     * Sets the value of the timeseries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Charttype.Timeseries }
     *     
     */
    public void setTimeseries(Charttype.Timeseries value) {
        this.timeseries = value;
    }

    public boolean isSetTimeseries() {
        return (this.timeseries!= null);
    }

    /**
     * Gets the value of the timebar property.
     * 
     * @return
     *     possible object is
     *     {@link Charttype.Timebar }
     *     
     */
    public Charttype.Timebar getTimebar() {
        return timebar;
    }

    /**
     * Sets the value of the timebar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Charttype.Timebar }
     *     
     */
    public void setTimebar(Charttype.Timebar value) {
        this.timebar = value;
    }

    public boolean isSetTimebar() {
        return (this.timebar!= null);
    }

    /**
     * Gets the value of the bar property.
     * 
     * @return
     *     possible object is
     *     {@link Charttype.Bar }
     *     
     */
    public Charttype.Bar getBar() {
        return bar;
    }

    /**
     * Sets the value of the bar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Charttype.Bar }
     *     
     */
    public void setBar(Charttype.Bar value) {
        this.bar = value;
    }

    public boolean isSetBar() {
        return (this.bar!= null);
    }

    /**
     * Gets the value of the gantt property.
     * 
     * @return
     *     possible object is
     *     {@link Charttype.Gantt }
     *     
     */
    public Charttype.Gantt getGantt() {
        return gantt;
    }

    /**
     * Sets the value of the gantt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Charttype.Gantt }
     *     
     */
    public void setGantt(Charttype.Gantt value) {
        this.gantt = value;
    }

    public boolean isSetGantt() {
        return (this.gantt!= null);
    }

    /**
     * Gets the value of the spline property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSpline() {
        return spline;
    }

    /**
     * Sets the value of the spline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSpline(Object value) {
        this.spline = value;
    }

    public boolean isSetSpline() {
        return (this.spline!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="vertical" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Bar
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute
        protected Boolean vertical;

        /**
         * Gets the value of the vertical property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isVertical() {
            return vertical;
        }

        /**
         * Sets the value of the vertical property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setVertical(boolean value) {
            this.vertical = value;
        }

        public boolean isSetVertical() {
            return (this.vertical!= null);
        }

        public void unsetVertical() {
            this.vertical = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="timePeriod" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Gantt
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute
        protected String timePeriod;

        /**
         * Gets the value of the timePeriod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTimePeriod() {
            return timePeriod;
        }

        /**
         * Sets the value of the timePeriod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTimePeriod(String value) {
            this.timePeriod = value;
        }

        public boolean isSetTimePeriod() {
            return (this.timePeriod!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="shadow" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="gradient" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Timebar
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute
        protected Boolean shadow;
        @XmlAttribute
        protected Boolean gradient;

        /**
         * Gets the value of the shadow property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isShadow() {
            return shadow;
        }

        /**
         * Sets the value of the shadow property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setShadow(boolean value) {
            this.shadow = value;
        }

        public boolean isSetShadow() {
            return (this.shadow!= null);
        }

        public void unsetShadow() {
            this.shadow = null;
        }

        /**
         * Gets the value of the gradient property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isGradient() {
            return gradient;
        }

        /**
         * Sets the value of the gradient property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setGradient(boolean value) {
            this.gradient = value;
        }

        public boolean isSetGradient() {
            return (this.gradient!= null);
        }

        public void unsetGradient() {
            this.gradient = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="gap" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="cumulate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="timePeriod" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Timeseries
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute
        protected Boolean gap;
        @XmlAttribute
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar from;
        @XmlAttribute
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar to;
        @XmlAttribute
        protected Boolean cumulate;
        @XmlAttribute
        protected String timePeriod;

        /**
         * Gets the value of the gap property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isGap() {
            return gap;
        }

        /**
         * Sets the value of the gap property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setGap(boolean value) {
            this.gap = value;
        }

        public boolean isSetGap() {
            return (this.gap!= null);
        }

        public void unsetGap() {
            this.gap = null;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFrom(XMLGregorianCalendar value) {
            this.from = value;
        }

        public boolean isSetFrom() {
            return (this.from!= null);
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTo(XMLGregorianCalendar value) {
            this.to = value;
        }

        public boolean isSetTo() {
            return (this.to!= null);
        }

        /**
         * Gets the value of the cumulate property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCumulate() {
            return cumulate;
        }

        /**
         * Sets the value of the cumulate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCumulate(boolean value) {
            this.cumulate = value;
        }

        public boolean isSetCumulate() {
            return (this.cumulate!= null);
        }

        public void unsetCumulate() {
            this.cumulate = null;
        }

        /**
         * Gets the value of the timePeriod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTimePeriod() {
            return timePeriod;
        }

        /**
         * Sets the value of the timePeriod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTimePeriod(String value) {
            this.timePeriod = value;
        }

        public boolean isSetTimePeriod() {
            return (this.timePeriod!= null);
        }

    }

}
