//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.14 at 09:21:41 AM MEZ 
//


package org.openfuxml.addon.chart.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfuxml.addon.chart.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfuxml.addon.chart.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Charttype }
     * 
     */
    public Charttype createCharttype() {
        return new Charttype();
    }

    /**
     * Create an instance of {@link Container }
     * 
     */
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link Chart.Size }
     * 
     */
    public Chart.Size createChartSize() {
        return new Chart.Size();
    }

    /**
     * Create an instance of {@link AxisType.Number }
     * 
     */
    public AxisType.Number createAxisTypeNumber() {
        return new AxisType.Number();
    }

    /**
     * Create an instance of {@link Charttype.Timebar }
     * 
     */
    public Charttype.Timebar createCharttypeTimebar() {
        return new Charttype.Timebar();
    }

    /**
     * Create an instance of {@link Charttype.Bar }
     * 
     */
    public Charttype.Bar createCharttypeBar() {
        return new Charttype.Bar();
    }

    /**
     * Create an instance of {@link AxisType.Number.Ticker }
     * 
     */
    public AxisType.Number.Ticker createAxisTypeNumberTicker() {
        return new AxisType.Number.Ticker();
    }

    /**
     * Create an instance of {@link Color }
     * 
     */
    public Color createColor() {
        return new Color();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Charttype.Timeseries }
     * 
     */
    public Charttype.Timeseries createCharttypeTimeseries() {
        return new Charttype.Timeseries();
    }

    /**
     * Create an instance of {@link AxisType.Date.Ticker }
     * 
     */
    public AxisType.Date.Ticker createAxisTypeDateTicker() {
        return new AxisType.Date.Ticker();
    }

    /**
     * Create an instance of {@link AxisType }
     * 
     */
    public AxisType createAxisType() {
        return new AxisType();
    }

    /**
     * Create an instance of {@link Axis }
     * 
     */
    public Axis createAxis() {
        return new Axis();
    }

    /**
     * Create an instance of {@link Chart.Colors }
     * 
     */
    public Chart.Colors createChartColors() {
        return new Chart.Colors();
    }

    /**
     * Create an instance of {@link Chart.Title }
     * 
     */
    public Chart.Title createChartTitle() {
        return new Chart.Title();
    }

    /**
     * Create an instance of {@link AxisType.Date }
     * 
     */
    public AxisType.Date createAxisTypeDate() {
        return new AxisType.Date();
    }

    /**
     * Create an instance of {@link Chart }
     * 
     */
    public Chart createChart() {
        return new Chart();
    }

    /**
     * Create an instance of {@link Chart.Grid }
     * 
     */
    public Chart.Grid createChartGrid() {
        return new Chart.Grid();
    }

    /**
     * Create an instance of {@link Charttype.Gantt }
     * 
     */
    public Charttype.Gantt createCharttypeGantt() {
        return new Charttype.Gantt();
    }

}
