//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.21 at 09:59:09 AM MESZ 
//


package org.openfuxml.addon.epub.data.jaxb.ncx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.daisy.org/z3986/2005/ncx/}head"/>
 *         &lt;element ref="{http://www.daisy.org/z3986/2005/ncx/}docTitle"/>
 *         &lt;element ref="{http://www.daisy.org/z3986/2005/ncx/}navMap"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "docTitle",
    "navMap"
})
@XmlRootElement(name = "ncx")
public class Ncx {

    @XmlElement(required = true)
    protected Head head;
    @XmlElement(required = true)
    protected DocTitle docTitle;
    @XmlElement(required = true)
    protected NavMap navMap;
    @XmlAttribute
    protected String version;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link Head }
     *     
     */
    public Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head }
     *     
     */
    public void setHead(Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the docTitle property.
     * 
     * @return
     *     possible object is
     *     {@link DocTitle }
     *     
     */
    public DocTitle getDocTitle() {
        return docTitle;
    }

    /**
     * Sets the value of the docTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocTitle }
     *     
     */
    public void setDocTitle(DocTitle value) {
        this.docTitle = value;
    }

    /**
     * Gets the value of the navMap property.
     * 
     * @return
     *     possible object is
     *     {@link NavMap }
     *     
     */
    public NavMap getNavMap() {
        return navMap;
    }

    /**
     * Sets the value of the navMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavMap }
     *     
     */
    public void setNavMap(NavMap value) {
        this.navMap = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
