package models;
public class TriangleFin implements FinInterface {
  private double l;
  private double w;
  private double t;
  private double Tsigma;
  private double Tb;
  private int N;
  private double k;
  private double h;
  private double biotNumber;
  private double A;
  private double P;
  private double m;
  private double Ac;
  private double Lc;
  private double tetab;
  private double convHeatT;
  private double adiabatic;
  private double infiniteLength;
  private double longFin;
  private double insulatedFin;
  public TriangleFin(  double l,  double w,  double t,  double Tsigma,  double Tb,  int N,  double k,  double h){
    models.TriangleFin genVar12;
    genVar12=this;
    genVar12.l=l;
    models.TriangleFin genVar13;
    genVar13=this;
    genVar13.w=w;
    models.TriangleFin genVar14;
    genVar14=this;
    genVar14.t=t;
    models.TriangleFin genVar15;
    genVar15=this;
    genVar15.Tsigma=Tsigma;
    models.TriangleFin genVar16;
    genVar16=this;
    genVar16.Tb=Tb;
    models.TriangleFin genVar17;
    genVar17=this;
    genVar17.N=N;
    models.TriangleFin genVar18;
    genVar18=this;
    genVar18.k=k;
    models.TriangleFin genVar19;
    genVar19=this;
    genVar19.h=h;
    models.TriangleFin genVar20;
    genVar20=this;
    models.TriangleFin genVar21;
    genVar21=this;
    int genVar22;
    genVar22=2;
    double genVar23;
    genVar23=l + w;
    double genVar24;
    genVar24=(genVar23);
    genVar20.A=genVar21.P=genVar22 * genVar24;
    models.TriangleFin genVar25;
    genVar25=this;
    int genVar26;
    genVar26=2;
    double genVar27;
    genVar27=l * l;
    double genVar28;
    genVar28=t * t;
    int genVar29;
    genVar29=4;
    double genVar30;
    genVar30=genVar28 / genVar29;
    double genVar31;
    genVar31=(genVar30);
    double genVar32;
    genVar32=genVar27 + genVar31;
    double genVar33;
    genVar33=Math.sqrt(genVar32);
    genVar25.Ac=genVar26 * w * genVar33;
    models.TriangleFin genVar34;
    genVar34=this;
    int genVar35;
    genVar35=2;
    double genVar36;
    genVar36=genVar35 * l * l* l;
    double genVar37;
    genVar37=k * w;
    double genVar38;
    genVar38=(genVar37);
    genVar34.m=genVar36 / genVar38;
    models.TriangleFin genVar39;
    genVar39=this;
    genVar39.Lc=l;
    models.TriangleFin genVar40;
    genVar40=this;
    genVar40.tetab=Tb - Tsigma;
    models.TriangleFin genVar41;
    genVar41=this;
    double genVar42;
    genVar42=Ac / P;
    double genVar43;
    genVar43=(genVar42);
    double genVar44;
    genVar44=h * genVar43;
    genVar41.biotNumber=genVar44 / k;
    models.TriangleFin genVar45;
    genVar45=this;
    double genVar46;
    genVar46=h * P * k* Ac;
    double genVar47;
    genVar47=Math.sqrt(genVar46);
    genVar45.infiniteLength=genVar47 * tetab;
    models.TriangleFin genVar48;
    genVar48=this;
    double genVar49;
    genVar49=m * Lc;
    double genVar50;
    genVar50=Math.tanh(genVar49);
    genVar48.adiabatic=infiniteLength * genVar50;
    models.TriangleFin genVar51;
    genVar51=this;
    double genVar52;
    genVar52=m * Lc;
    double genVar53;
    genVar53=Math.sinh(genVar52);
    double genVar54;
    genVar54=m * k;
    double genVar55;
    genVar55=(genVar54);
    double genVar56;
    genVar56=h / genVar55;
    double genVar57;
    genVar57=(genVar56);
    double genVar58;
    genVar58=m * Lc;
    double genVar59;
    genVar59=Math.cosh(genVar58);
    double genVar60;
    genVar60=genVar57 * genVar59;
    double genVar61;
    genVar61=genVar53 + genVar60;
    double genVar62;
    genVar62=(genVar61);
    double genVar63;
    genVar63=m * Lc;
    double genVar64;
    genVar64=Math.cosh(genVar63);
    double genVar65;
    genVar65=m * k;
    double genVar66;
    genVar66=(genVar65);
    double genVar67;
    genVar67=h / genVar66;
    double genVar68;
    genVar68=(genVar67);
    double genVar69;
    genVar69=m * Lc;
    double genVar70;
    genVar70=Math.sinh(genVar69);
    double genVar71;
    genVar71=genVar68 * genVar70;
    double genVar72;
    genVar72=genVar64 + genVar71;
    double genVar73;
    genVar73=(genVar72);
    double genVar74;
    genVar74=genVar62 / genVar73;
    double genVar75;
    genVar75=(genVar74);
    genVar51.convHeatT=infiniteLength * genVar75;
    models.TriangleFin genVar76;
    genVar76=this;
    int genVar77;
    genVar77=1;
    double genVar78;
    genVar78=m * l;
    double genVar79;
    genVar79=(genVar78);
    genVar76.longFin=genVar77 / genVar79;
    models.TriangleFin genVar80;
    genVar80=this;
    double genVar81;
    genVar81=m * l;
    double genVar82;
    genVar82=Math.tanh(genVar81);
    double genVar83;
    genVar83=m * l;
    double genVar84;
    genVar84=(genVar83);
    genVar80.insulatedFin=genVar82 / genVar84;
  }
  @Override public double getBiotNumber(){
    return biotNumber;
  }
  @Override public double getConvHeatT(){
    double genVar85;
    genVar85=convHeatT * N;
    return genVar85;
  }
  @Override public double getAdiabatic(){
    double genVar86;
    genVar86=adiabatic * N;
    return genVar86;
  }
  @Override public double getInfiniteLength(){
    double genVar87;
    genVar87=infiniteLength * N;
    return genVar87;
  }
  @Override public double getLongFin(){
    return longFin;
  }
  @Override public double getInsulatedFin(){
    return insulatedFin;
  }
}
