//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.08 at 01:51:17 PM MEZ 
//


package org.openfuxml.addon.jsfapp.data.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openfuxml.org/jsfapp}iframe"/>
 *         &lt;element ref="{http://www.openfuxml.org/jsfapp}jsf"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xsrc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iframe",
    "jsf"
})
@XmlRootElement(name = "ofxinjection")
public class Ofxinjection
    implements Serializable
{

    private final static long serialVersionUID = 14L;
    @XmlElement(required = true)
    protected Iframe iframe;
    @XmlElement(required = true)
    protected Jsf jsf;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String xsrc;

    /**
     * Gets the value of the iframe property.
     * 
     * @return
     *     possible object is
     *     {@link Iframe }
     *     
     */
    public Iframe getIframe() {
        return iframe;
    }

    /**
     * Sets the value of the iframe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Iframe }
     *     
     */
    public void setIframe(Iframe value) {
        this.iframe = value;
    }

    public boolean isSetIframe() {
        return (this.iframe!= null);
    }

    /**
     * Gets the value of the jsf property.
     * 
     * @return
     *     possible object is
     *     {@link Jsf }
     *     
     */
    public Jsf getJsf() {
        return jsf;
    }

    /**
     * Sets the value of the jsf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Jsf }
     *     
     */
    public void setJsf(Jsf value) {
        this.jsf = value;
    }

    public boolean isSetJsf() {
        return (this.jsf!= null);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id!= null);
    }

    /**
     * Gets the value of the xsrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXsrc() {
        return xsrc;
    }

    /**
     * Sets the value of the xsrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXsrc(String value) {
        this.xsrc = value;
    }

    public boolean isSetXsrc() {
        return (this.xsrc!= null);
    }

}
