//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.21 at 09:59:09 AM MESZ 
//


package org.openfuxml.addon.epub.data.jaxb.ncx;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfuxml.addon.epub.data.jaxb.ncx package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfuxml.addon.epub.data.jaxb.ncx
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NavMap.NavPoint.Content }
     * 
     */
    public NavMap.NavPoint.Content createNavMapNavPointContent() {
        return new NavMap.NavPoint.Content();
    }

    /**
     * Create an instance of {@link DocTitle }
     * 
     */
    public DocTitle createDocTitle() {
        return new DocTitle();
    }

    /**
     * Create an instance of {@link NavMap }
     * 
     */
    public NavMap createNavMap() {
        return new NavMap();
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link NavMap.NavPoint }
     * 
     */
    public NavMap.NavPoint createNavMapNavPoint() {
        return new NavMap.NavPoint();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Ncx }
     * 
     */
    public Ncx createNcx() {
        return new Ncx();
    }

    /**
     * Create an instance of {@link NavMap.NavPoint.NavLabel }
     * 
     */
    public NavMap.NavPoint.NavLabel createNavMapNavPointNavLabel() {
        return new NavMap.NavPoint.NavLabel();
    }

    /**
     * Create an instance of {@link Head.Meta }
     * 
     */
    public Head.Meta createHeadMeta() {
        return new Head.Meta();
    }

}
