//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.21 at 09:59:09 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.daisy.org/z3986/2005/ncx/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openfuxml.addon.epub.data.jaxb.ncx;
