//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.13 at 05:10:55 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openfuxml.org/chart")
package org.openfuxml.addon.chart.jaxb;
