#!/bin/bash

#       ********************************************************************
#		$Id: postinst,v 1.4 2007/03/02 13:17:25 hemmer Exp $
#		********************************************************************
#		*******************************************************************************
#		| openFuXML open source                                                       |
#		*******************************************************************************
#		| Copyright (c) 2002-2006 openFuXML open source, University of Hagen          |
#		|                                                                             |
#		| This program is free software; you can redistribute it and/or               |
#		| modify it under the terms of the GNU General Public License                 |
#		| as published by the Free Software Foundation; either version 2              |
#		| of the License, or (at your option) any later version.                      |
#		|                                                                             |
#		| This program is distributed in the hope that it will be useful,             |
#		| but WITHOUT ANY WARRANTY; without even the implied warranty of              |
#		| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               |
#		| GNU General Public License for more details.                                |
#		|                                                                             |
#		| You should have received a copy of the GNU General Public License           |
#		| along with this program; if not, write to the Free Software                 |
#		| Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. |
#		*******************************************************************************
#		******************************************************************** 
  


# ----------------------------------------------
# DEFINITION VON FUNKTIONEN UND VARIABLEN
# ----------------------------------------------


# Da Java nicht mit Hilfe dieses Skripts installiert werden kann, es aber 
# benötigt wird, soll zuerst eine Abfrage nach einer kompatiblen Java Version
# gestartet werden.
function checkjava()
{
   echo "Teste, ob Java in einer kompatiblen Version installiert ist..."

#  if schleife, die den output von "java -version" oä checkt
#  echo "Java Version kompatibel, setze Installation fort..."


   echo""
   echo "Bitte laden Sie sich von http://java.sun.com das aktuelle
   Java Development Kit (z.B. jdk-1_5_0_08-linux-i586.bin) herunter und
   installieren Sie es gemäß der Anleitung in der openFuXML Dokumentation."
   echo ""
   echo ""
}

rcdir='/etc/rc'


# Formatierte Ausgabe des Namens einer neuen Untersektion des Skriptablaufs
function newsection()
{
  echo ""
  echo ""
  echo "---------------------------------------------------------------------"
  echo $1
  echo "---------------------------------------------------------------------"
  echo ""
  echo ""
}


# ----------------------------------------------
# BEGINN DES EIGENTLICHEN SKRIPTS
# ----------------------------------------------

newsection "openFuXML @@@openfuxml-version@@@ Installation"

checkjava

#Benutzer wird angelegt
echo "Lege Benutzer fuxml mit Passwort fuxml und Home Verzeichnis an..."
echo ""
# Das Passwort ist ein MD5 Hash von fuxml
useradd fuxml -m -p '$1$7EUse1$CVELvd0jB1/nP2OoIdDUl.'
echo ""
echo ""

newsection "Kopiere und Entpacke Dateien, setze Rechte und konfiguriere... "

cd /root
cp ./openFuXML-System-@@@openfuxml-version@@@s.tgz /home/fuxml
rm openFuXML-System-@@@openfuxml-version@@@s.tgz
cd /home/fuxml
su fuxml -c "tar -xzf openFuXML-System-@@@openfuxml-version@@@s.tgz"
cd openFuXML-@@@openfuxml-version@@@
su fuxml -c "chmod +x openFuXML.sh"
su fuxml -c "chmod +x openFuXML"
su fuxml -c "chmod +x lib/apache-ant-@@@ant-version@@@/bin/antRun"

newsection "Erstelle Backup der Tex for Hypertext Kontrolldateien"

if [ -f /usr/share/texmf/tex/generic/tex4ht/tex4ht.env ]; then
  cp /usr/share/texmf/tex/generic/tex4ht/tex4ht.env /usr/share/texmf/tex/generic/tex4ht/tex4ht_openFuXML_backup.env
else 
  echo "Backup nicht nötig, Datei nicht vorhanden.."
fi

if [ -f /usr/bin/htlatex ]; then
  cp /usr/bin/htlatex /usr/bin/htlatex_openFuXML_backup.env
else 
  echo "backup nicht nötig, Datei nicht vorhanden"
fi

cp applications/fuxml/formats/math/ht4t_files/tex4ht_fuxml.env /usr/share/texmf/tex/generic/tex4ht/tex4ht.env
cp applications/fuxml/formats/math/ht4t_files/htlatex /usr/bin/htlatex
chmod +x /usr/bin/htlatex

cp openFuXML /etc/init.d

echo "[openfuxml]
        comment = openFuXML-Share
        path = /home/fuxml/openFuXML-@@@openfuxml-version@@@/share
	writeable = yes
	browseable = yes" >> /etc/samba/smb.conf

newsection "Konfiguration des Samba Benutzers fuxml"

smbpasswd -a fuxml

if [ $1x = "noauto" ]; then
  echo""
  echo""
else
   newsection "Konfiguriere Runlevel Definitionen für automatischen Start/Stop..."
   echo ""
   cd ${rcdir}2.d
   ln -s ../init.d/openFuXML S22openFuXML
   cd ${rcdir}5.d
   ln -s ../init.d/openFuXML S22openFuXML
   cd ${rcdir}0.d
   ln -s ../init.d/openFuXML K22openFuXML
   echo ""
   echo ""
fi

newsection "Beende Installation, starte openFuXML Server..."

rm /home/fuxml/openFuXML-System-@@@openfuxml-version@@@s.tgz
cd /home/fuxml/openFuXML-@@@openfuxml-version@@@/
/etc/init.d/openFuXML start
#rm $0