//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.21 at 09:26:05 AM MESZ 
//


package org.openfuxml.addon.epub.data.jaxb.container;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rootfiles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rootfile" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="full-path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="media-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rootfiles"
})
@XmlRootElement(name = "container")
public class Container {

    @XmlElement(required = true)
    protected Container.Rootfiles rootfiles;
    @XmlAttribute
    protected String version;

    /**
     * Gets the value of the rootfiles property.
     * 
     * @return
     *     possible object is
     *     {@link Container.Rootfiles }
     *     
     */
    public Container.Rootfiles getRootfiles() {
        return rootfiles;
    }

    /**
     * Sets the value of the rootfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Container.Rootfiles }
     *     
     */
    public void setRootfiles(Container.Rootfiles value) {
        this.rootfiles = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rootfile" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="full-path" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="media-type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rootfile"
    })
    public static class Rootfiles {

        @XmlElement(required = true)
        protected List<Container.Rootfiles.Rootfile> rootfile;

        /**
         * Gets the value of the rootfile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rootfile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRootfile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Container.Rootfiles.Rootfile }
         * 
         * 
         */
        public List<Container.Rootfiles.Rootfile> getRootfile() {
            if (rootfile == null) {
                rootfile = new ArrayList<Container.Rootfiles.Rootfile>();
            }
            return this.rootfile;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="full-path" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="media-type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Rootfile {

            @XmlAttribute(name = "full-path")
            protected String fullPath;
            @XmlAttribute(name = "media-type")
            protected String mediaType;

            /**
             * Gets the value of the fullPath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFullPath() {
                return fullPath;
            }

            /**
             * Sets the value of the fullPath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFullPath(String value) {
                this.fullPath = value;
            }

            /**
             * Gets the value of the mediaType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMediaType() {
                return mediaType;
            }

            /**
             * Sets the value of the mediaType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMediaType(String value) {
                this.mediaType = value;
            }

        }

    }

}
