//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.09 at 09:23:59 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openfuxml.org/list", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openfuxml.content.ofx.list;
