package com.fray.evo.action;
import com.fray.evo.action.build.EcActionBuildBaneling;
import com.fray.evo.action.build.EcActionBuildBanelingNest;
import com.fray.evo.action.build.EcActionBuildBroodLord;
import com.fray.evo.action.build.EcActionBuildCorruptor;
import com.fray.evo.action.build.EcActionBuildDrone;
import com.fray.evo.action.build.EcActionBuildEvolutionChamber;
import com.fray.evo.action.build.EcActionBuildExtractor;
import com.fray.evo.action.build.EcActionBuildGreaterSpire;
import com.fray.evo.action.build.EcActionBuildHatchery;
import com.fray.evo.action.build.EcActionBuildHive;
import com.fray.evo.action.build.EcActionBuildHydralisk;
import com.fray.evo.action.build.EcActionBuildHydraliskDen;
import com.fray.evo.action.build.EcActionBuildInfestationPit;
import com.fray.evo.action.build.EcActionBuildInfestor;
import com.fray.evo.action.build.EcActionBuildLair;
import com.fray.evo.action.build.EcActionBuildMutalisk;
import com.fray.evo.action.build.EcActionBuildNydusNetwork;
import com.fray.evo.action.build.EcActionBuildNydusWorm;
import com.fray.evo.action.build.EcActionBuildOverlord;
import com.fray.evo.action.build.EcActionBuildOverseer;
import com.fray.evo.action.build.EcActionBuildQueen;
import com.fray.evo.action.build.EcActionBuildRoach;
import com.fray.evo.action.build.EcActionBuildRoachWarren;
import com.fray.evo.action.build.EcActionBuildSpawningPool;
import com.fray.evo.action.build.EcActionBuildSpineCrawler;
import com.fray.evo.action.build.EcActionBuildSpire;
import com.fray.evo.action.build.EcActionBuildSporeCrawler;
import com.fray.evo.action.build.EcActionBuildUltralisk;
import com.fray.evo.action.build.EcActionBuildUltraliskCavern;
import com.fray.evo.action.build.EcActionBuildZergling;
import com.fray.evo.action.upgrade.*;
import com.fray.evo.util.Buildable;
import com.fray.evo.util.ZergBuildingLibrary;
import com.fray.evo.util.ZergUnitLibrary;
import com.fray.evo.util.ZergUpgradeLibrary;
import java.util.HashMap;
/** 
 * @author Cyrik
 */
public final class ActionManager {
  private static HashMap<Buildable,EcAction> buildableToActionMap;
  synchronized static public EcAction getActionFor(  Buildable buildable){
    boolean genVar1628;
    genVar1628=buildableToActionMap == null;
    if (genVar1628) {
      init();
    }
 else {
      ;
    }
    com.fray.evo.action.EcAction genVar1630;
    genVar1630=buildableToActionMap.get(buildable);
    return genVar1630;
  }
  private static void init(){
    buildableToActionMap=new HashMap<Buildable,EcAction>();
    com.fray.evo.action.upgrade.EcActionUpgradeAdrenalGlands genVar1631;
    genVar1631=new EcActionUpgradeAdrenalGlands();
    buildableToActionMap.put(ZergUpgradeLibrary.AdrenalGlands,genVar1631);
    com.fray.evo.action.upgrade.EcActionUpgradeCarapace1 genVar1632;
    genVar1632=new EcActionUpgradeCarapace1();
    buildableToActionMap.put(ZergUpgradeLibrary.Armor1,genVar1632);
    com.fray.evo.action.upgrade.EcActionUpgradeCarapace2 genVar1633;
    genVar1633=new EcActionUpgradeCarapace2();
    buildableToActionMap.put(ZergUpgradeLibrary.Armor2,genVar1633);
    com.fray.evo.action.upgrade.EcActionUpgradeCarapace3 genVar1634;
    genVar1634=new EcActionUpgradeCarapace3();
    buildableToActionMap.put(ZergUpgradeLibrary.Armor3,genVar1634);
    com.fray.evo.action.upgrade.EcActionUpgradeBurrow genVar1635;
    genVar1635=new EcActionUpgradeBurrow();
    buildableToActionMap.put(ZergUpgradeLibrary.Burrow,genVar1635);
    com.fray.evo.action.upgrade.EcActionUpgradeCentrifugalHooks genVar1636;
    genVar1636=new EcActionUpgradeCentrifugalHooks();
    buildableToActionMap.put(ZergUpgradeLibrary.CentrifugalHooks,genVar1636);
    com.fray.evo.action.upgrade.EcActionUpgradeChitinousPlating genVar1637;
    genVar1637=new EcActionUpgradeChitinousPlating();
    buildableToActionMap.put(ZergUpgradeLibrary.ChitinousPlating,genVar1637);
    com.fray.evo.action.upgrade.EcActionUpgradeFlyerArmor1 genVar1638;
    genVar1638=new EcActionUpgradeFlyerArmor1();
    buildableToActionMap.put(ZergUpgradeLibrary.FlyerArmor1,genVar1638);
    com.fray.evo.action.upgrade.EcActionUpgradeFlyerArmor2 genVar1639;
    genVar1639=new EcActionUpgradeFlyerArmor2();
    buildableToActionMap.put(ZergUpgradeLibrary.FlyerArmor2,genVar1639);
    com.fray.evo.action.upgrade.EcActionUpgradeFlyerArmor3 genVar1640;
    genVar1640=new EcActionUpgradeFlyerArmor3();
    buildableToActionMap.put(ZergUpgradeLibrary.FlyerArmor3,genVar1640);
    com.fray.evo.action.upgrade.EcActionUpgradeFlyerAttacks1 genVar1641;
    genVar1641=new EcActionUpgradeFlyerAttacks1();
    buildableToActionMap.put(ZergUpgradeLibrary.FlyerAttacks1,genVar1641);
    com.fray.evo.action.upgrade.EcActionUpgradeFlyerAttacks2 genVar1642;
    genVar1642=new EcActionUpgradeFlyerAttacks2();
    buildableToActionMap.put(ZergUpgradeLibrary.FlyerAttacks2,genVar1642);
    com.fray.evo.action.upgrade.EcActionUpgradeFlyerAttacks3 genVar1643;
    genVar1643=new EcActionUpgradeFlyerAttacks3();
    buildableToActionMap.put(ZergUpgradeLibrary.FlyerAttacks3,genVar1643);
    com.fray.evo.action.upgrade.EcActionUpgradeGlialReconstitution genVar1644;
    genVar1644=new EcActionUpgradeGlialReconstitution();
    buildableToActionMap.put(ZergUpgradeLibrary.GlialReconstitution,genVar1644);
    com.fray.evo.action.upgrade.EcActionUpgradeGroovedSpines genVar1645;
    genVar1645=new EcActionUpgradeGroovedSpines();
    buildableToActionMap.put(ZergUpgradeLibrary.GroovedSpines,genVar1645);
    com.fray.evo.action.upgrade.EcActionUpgradeMelee1 genVar1646;
    genVar1646=new EcActionUpgradeMelee1();
    buildableToActionMap.put(ZergUpgradeLibrary.Melee1,genVar1646);
    com.fray.evo.action.upgrade.EcActionUpgradeMelee2 genVar1647;
    genVar1647=new EcActionUpgradeMelee2();
    buildableToActionMap.put(ZergUpgradeLibrary.Melee2,genVar1647);
    com.fray.evo.action.upgrade.EcActionUpgradeMelee3 genVar1648;
    genVar1648=new EcActionUpgradeMelee3();
    buildableToActionMap.put(ZergUpgradeLibrary.Melee3,genVar1648);
    com.fray.evo.action.upgrade.EcActionUpgradeMetabolicBoost genVar1649;
    genVar1649=new EcActionUpgradeMetabolicBoost();
    buildableToActionMap.put(ZergUpgradeLibrary.MetabolicBoost,genVar1649);
    com.fray.evo.action.upgrade.EcActionUpgradeMissile1 genVar1650;
    genVar1650=new EcActionUpgradeMissile1();
    buildableToActionMap.put(ZergUpgradeLibrary.Missile1,genVar1650);
    com.fray.evo.action.upgrade.EcActionUpgradeMissile2 genVar1651;
    genVar1651=new EcActionUpgradeMissile2();
    buildableToActionMap.put(ZergUpgradeLibrary.Missile2,genVar1651);
    com.fray.evo.action.upgrade.EcActionUpgradeMissile3 genVar1652;
    genVar1652=new EcActionUpgradeMissile3();
    buildableToActionMap.put(ZergUpgradeLibrary.Missile3,genVar1652);
    com.fray.evo.action.upgrade.EcActionUpgradeNeuralParasite genVar1653;
    genVar1653=new EcActionUpgradeNeuralParasite();
    buildableToActionMap.put(ZergUpgradeLibrary.NeuralParasite,genVar1653);
    com.fray.evo.action.upgrade.EcActionUpgradePathogenGlands genVar1654;
    genVar1654=new EcActionUpgradePathogenGlands();
    buildableToActionMap.put(ZergUpgradeLibrary.PathogenGlands,genVar1654);
    com.fray.evo.action.upgrade.EcActionUpgradePneumatizedCarapace genVar1655;
    genVar1655=new EcActionUpgradePneumatizedCarapace();
    buildableToActionMap.put(ZergUpgradeLibrary.PneumatizedCarapace,genVar1655);
    com.fray.evo.action.upgrade.EcActionUpgradeTunnelingClaws genVar1656;
    genVar1656=new EcActionUpgradeTunnelingClaws();
    buildableToActionMap.put(ZergUpgradeLibrary.TunnelingClaws,genVar1656);
    com.fray.evo.action.upgrade.EcActionUpgradeVentralSacs genVar1657;
    genVar1657=new EcActionUpgradeVentralSacs();
    buildableToActionMap.put(ZergUpgradeLibrary.VentralSacs,genVar1657);
    com.fray.evo.action.build.EcActionBuildBanelingNest genVar1658;
    genVar1658=new EcActionBuildBanelingNest();
    buildableToActionMap.put(ZergBuildingLibrary.BanelingNest,genVar1658);
    com.fray.evo.action.build.EcActionBuildEvolutionChamber genVar1659;
    genVar1659=new EcActionBuildEvolutionChamber();
    buildableToActionMap.put(ZergBuildingLibrary.EvolutionChamber,genVar1659);
    com.fray.evo.action.build.EcActionBuildExtractor genVar1660;
    genVar1660=new EcActionBuildExtractor();
    buildableToActionMap.put(ZergBuildingLibrary.Extractor,genVar1660);
    com.fray.evo.action.build.EcActionBuildGreaterSpire genVar1661;
    genVar1661=new EcActionBuildGreaterSpire();
    buildableToActionMap.put(ZergBuildingLibrary.GreaterSpire,genVar1661);
    com.fray.evo.action.build.EcActionBuildHatchery genVar1662;
    genVar1662=new EcActionBuildHatchery();
    buildableToActionMap.put(ZergBuildingLibrary.Hatchery,genVar1662);
    com.fray.evo.action.build.EcActionBuildHive genVar1663;
    genVar1663=new EcActionBuildHive();
    buildableToActionMap.put(ZergBuildingLibrary.Hive,genVar1663);
    com.fray.evo.action.build.EcActionBuildHydraliskDen genVar1664;
    genVar1664=new EcActionBuildHydraliskDen();
    buildableToActionMap.put(ZergBuildingLibrary.HydraliskDen,genVar1664);
    com.fray.evo.action.build.EcActionBuildInfestationPit genVar1665;
    genVar1665=new EcActionBuildInfestationPit();
    buildableToActionMap.put(ZergBuildingLibrary.InfestationPit,genVar1665);
    com.fray.evo.action.build.EcActionBuildLair genVar1666;
    genVar1666=new EcActionBuildLair();
    buildableToActionMap.put(ZergBuildingLibrary.Lair,genVar1666);
    com.fray.evo.action.build.EcActionBuildNydusNetwork genVar1667;
    genVar1667=new EcActionBuildNydusNetwork();
    buildableToActionMap.put(ZergBuildingLibrary.NydusNetwork,genVar1667);
    com.fray.evo.action.build.EcActionBuildNydusWorm genVar1668;
    genVar1668=new EcActionBuildNydusWorm();
    buildableToActionMap.put(ZergBuildingLibrary.NydusWorm,genVar1668);
    com.fray.evo.action.build.EcActionBuildRoachWarren genVar1669;
    genVar1669=new EcActionBuildRoachWarren();
    buildableToActionMap.put(ZergBuildingLibrary.RoachWarren,genVar1669);
    com.fray.evo.action.build.EcActionBuildSpawningPool genVar1670;
    genVar1670=new EcActionBuildSpawningPool();
    buildableToActionMap.put(ZergBuildingLibrary.SpawningPool,genVar1670);
    com.fray.evo.action.build.EcActionBuildSpineCrawler genVar1671;
    genVar1671=new EcActionBuildSpineCrawler();
    buildableToActionMap.put(ZergBuildingLibrary.SpineCrawler,genVar1671);
    com.fray.evo.action.build.EcActionBuildSpire genVar1672;
    genVar1672=new EcActionBuildSpire();
    buildableToActionMap.put(ZergBuildingLibrary.Spire,genVar1672);
    com.fray.evo.action.build.EcActionBuildSporeCrawler genVar1673;
    genVar1673=new EcActionBuildSporeCrawler();
    buildableToActionMap.put(ZergBuildingLibrary.SporeCrawler,genVar1673);
    com.fray.evo.action.build.EcActionBuildUltraliskCavern genVar1674;
    genVar1674=new EcActionBuildUltraliskCavern();
    buildableToActionMap.put(ZergBuildingLibrary.UltraliskCavern,genVar1674);
    com.fray.evo.action.build.EcActionBuildBaneling genVar1675;
    genVar1675=new EcActionBuildBaneling();
    buildableToActionMap.put(ZergUnitLibrary.Baneling,genVar1675);
    com.fray.evo.action.build.EcActionBuildBroodLord genVar1676;
    genVar1676=new EcActionBuildBroodLord();
    buildableToActionMap.put(ZergUnitLibrary.Broodlord,genVar1676);
    com.fray.evo.action.build.EcActionBuildCorruptor genVar1677;
    genVar1677=new EcActionBuildCorruptor();
    buildableToActionMap.put(ZergUnitLibrary.Corruptor,genVar1677);
    com.fray.evo.action.build.EcActionBuildDrone genVar1678;
    genVar1678=new EcActionBuildDrone();
    buildableToActionMap.put(ZergUnitLibrary.Drone,genVar1678);
    com.fray.evo.action.build.EcActionBuildHydralisk genVar1679;
    genVar1679=new EcActionBuildHydralisk();
    buildableToActionMap.put(ZergUnitLibrary.Hydralisk,genVar1679);
    com.fray.evo.action.build.EcActionBuildInfestor genVar1680;
    genVar1680=new EcActionBuildInfestor();
    buildableToActionMap.put(ZergUnitLibrary.Infestor,genVar1680);
    com.fray.evo.action.build.EcActionBuildMutalisk genVar1681;
    genVar1681=new EcActionBuildMutalisk();
    buildableToActionMap.put(ZergUnitLibrary.Mutalisk,genVar1681);
    com.fray.evo.action.build.EcActionBuildOverlord genVar1682;
    genVar1682=new EcActionBuildOverlord();
    buildableToActionMap.put(ZergUnitLibrary.Overlord,genVar1682);
    com.fray.evo.action.build.EcActionBuildOverseer genVar1683;
    genVar1683=new EcActionBuildOverseer();
    buildableToActionMap.put(ZergUnitLibrary.Overseer,genVar1683);
    com.fray.evo.action.build.EcActionBuildQueen genVar1684;
    genVar1684=new EcActionBuildQueen();
    buildableToActionMap.put(ZergUnitLibrary.Queen,genVar1684);
    com.fray.evo.action.build.EcActionBuildRoach genVar1685;
    genVar1685=new EcActionBuildRoach();
    buildableToActionMap.put(ZergUnitLibrary.Roach,genVar1685);
    com.fray.evo.action.build.EcActionBuildUltralisk genVar1686;
    genVar1686=new EcActionBuildUltralisk();
    buildableToActionMap.put(ZergUnitLibrary.Ultralisk,genVar1686);
    com.fray.evo.action.build.EcActionBuildZergling genVar1687;
    genVar1687=new EcActionBuildZergling();
    buildableToActionMap.put(ZergUnitLibrary.Zergling,genVar1687);
  }
}
