//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.15 at 10:14:57 PM MESZ 
//


package org.openfuxml.addon.jsfapp.data.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="jsfile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "jsf")
public class Jsf
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "jsfile")
    protected String jsfile;

    /**
     * Gets the value of the jsfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJsfile() {
        return jsfile;
    }

    /**
     * Sets the value of the jsfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJsfile(String value) {
        this.jsfile = value;
    }

    public boolean isSetJsfile() {
        return (this.jsfile!= null);
    }

}
