//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.30 at 09:41:11 AM MESZ 
//


package org.openfuxml.content.fuxml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openfuxml.content.fuxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openfuxml.content.fuxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Grafik }
     * 
     */
    public Grafik createGrafik() {
        return new Grafik();
    }

    /**
     * Create an instance of {@link AbsatzOhne }
     * 
     */
    public AbsatzOhne createAbsatzOhne() {
        return new AbsatzOhne();
    }

    /**
     * Create an instance of {@link Medienobjekt }
     * 
     */
    public Medienobjekt createMedienobjekt() {
        return new Medienobjekt();
    }

    /**
     * Create an instance of {@link Medienobjekt.Objekttitel }
     * 
     */
    public Medienobjekt.Objekttitel createMedienobjektObjekttitel() {
        return new Medienobjekt.Objekttitel();
    }

}
